version: 2

seeds:
  - name: dim_products
    description: "Synthetic product dimension table"
    columns:
      - name: product_id
        description: "Primary key for products"
        tests:
          - unique
          - not_null

      - name: product_sku
        description: "SKU in the format SKU-####"
        tests:
          - not_null

      - name: product_name
        description: "Human-readable product name"
        tests:
          - not_null

      - name: tier
        description: "Product tier"
        tests:
          - accepted_values:
              values: ["Premium", "Standard"]

      - name: purchase_price
        description: "Purchase price in USD"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"

      - name: transaction_type
        description: "Type of transaction for the product"
        tests:
          - accepted_values:
              values: ["BattlePass", "Emote", "Skin"]

      - name: is_recurring
        description: "Boolean flag for recurring products"
        tests:
          - accepted_values:
              values: [true, false]

      - name: cycle
        description: "Billing cycle for recurring products (M/Y), null if non-recurring"
        tests:
          - accepted_values:
              values: ["M", "Y", null]

      - name: created_at
        description: "Record creation timestamp"
        tests:
          - not_null

      - name: last_modified_at
        description: "Last modification timestamp"
        tests:
          - not_null
